index.html
server/controllers/orderController.js
server/index.js
server/migrations/20241217071011_users_and_orders.js
server/routes/orderRoutes.js
src/App.jsx
src/components/PaymentPage.jsx
src/pages/buyer/Dashboard.jsx
src/pages/buyer/Orders.jsx
src/services/cartService.jsx

migration files created 

---

package-lock.json
package.json
server/index.js
src/App.jsx
src/components/TopBar/TopBar.jsx
src/context/CartContext.jsx
src/layouts/BuyerLayout.jsx
src/pages/buyer/Dashboard.jsx

checkout starting

---

src/layouts/BuyerLayout.jsx
src/pages/buyer/Dashboard.jsx

top bar layout

---

server/migrations/20241216080043_create_products__table.js
server/migrations/20241217071011_users_and_orders.js
src/components/TopBar/TopBar.jsx
src/pages/buyer/Dashboard.jsx

migration file updated

---

server/controllers/userController.js
server/package-lock.json
server/package.json
src/components/TopBar/TopBar.jsx
src/pages/Login/LoginPage.jsx
src/pages/Signup/SignupPage.jsx

add to cart functionality

---

src/App.jsx
src/components/ProductCard.jsx
src/components/TopBar/TopBar.jsx
src/layouts/BuyerLayout.jsx
src/layouts/UserLayout.jsx
src/pages/Login/LoginPage.jsx
src/pages/buyer/UserDashboard.jsx

user logged

---

src/pages/Signup/SignupPage.jsx

body parser

---

src/App.jsx
src/components/PaymentPage.jsx
src/pages/buyer/UserCart.jsx

pagment page for the buyer

---

src/App.jsx
src/components/AddCategoryForm.jsx
src/layouts/AdminLayout.jsx
src/pages/admin/AddCategory.jsx
src/pages/admin/ProductManagement.jsx

Now admin can post the category of the product

Now admin can post the category of the product

---

server/controllers/userController.js

Cart error resolved

---

server/controllers/addressController.js
src/components/FinalPaymentPage.jsx
src/components/PaymentPage.jsx

order created

---

package-lock.json
package.json
server/controllers/loggedUserController.js
server/index.js
server/routes/loggedUserRouts.js
src/App.jsx
src/components/TopBar/UserTopbar.jsx
src/pages/Login/LoginPage.jsx
src/pages/buyer/UserDashboard.jsx
src/services/UserCartService.jsx

user can directly login from the dashboard of the buyer

user can directly login from the dashboard of the buyer

---

server/controllers/loggedUserController.js
server/routes/loggedUserRouts.js
src/components/TopBar/UserTopbar.jsx

real cart_product updating

---

src/App.jsx
src/components/TopBar/UserTopbar.jsx

buyer route changed 

---

server/controllers/userController.js
src/components/TopBar/TopBar.jsx
src/components/sidebar/Sidebar.jsx
src/pages/buyer/UserDashboard.jsx

Working on orders

---

src/App.jsx
src/components/sidebar/Sidebar.jsx
src/pages/buyer/Orders.jsx
src/pages/buyer/UserDashboard.jsx

user can see the order they cerated in the left side bar section

user can see the order they cerated

---

server/controllers/subcategoryController.js
server/index.js
server/migrations/20241216080043_create_products__table.js
server/routes/productRoutes.js
server/routes/subcatgoryRouts.js
src/App.jsx
src/components/AddProductForm.jsx
src/components/SubcategoryForm.jsx
src/layouts/AdminLayout.jsx
src/pages/admin/AddSubcategory.jsx
src/pages/buyer/Dashboard.jsx
src/services/subcategoryService.js

subcategory implemented

---

server/controllers/loggedUserController.js
server/controllers/sellerController.js
server/index.js
server/migrations/20250106091456_alter_users_and_create_sellers.js
server/routes/sellerRoutes.js
src/App.jsx
src/layouts/AdminLayout.jsx
src/pages/admin/OnboardSupplier.jsx

seller registration and waiting  for admin approval implemented

seller registration and waiting  for admin approval implemented 

---

server/controllers/sellerController.js
server/routes/sellerRoutes.js
src/pages/admin/OnboardSupplier.jsx

Now admin can approve and deny the suppliers

Now admin can approve and deny the suppliers

---

src/App.jsx
src/layouts/AdminLayout.jsx
src/pages/admin/AddCatalog.jsx

catalog form

---

server/controllers/catalogController.js
server/index.js
server/routes/catalogRoutes.js
src/pages/admin/AddCatalog.jsx

Catalog insertion implemented

---

server/controllers/loggedUserController.js
server/controllers/userController.js
server/routes/loggedUserRouts.js
src/App.jsx
src/components/TopBar/UserTopbar.jsx
src/components/sidebar/Sidebar.jsx
src/layouts/BuyerLayout.jsx
src/pages/buyer/Wishlist.jsx
src/services/wishlistService.jsx

Wish list for the user dashboard  is done

Wish list for the user dashboard  is done

---

src/App.jsx
src/layouts/BuyerLayout.jsx

wish list errors fixed

---

server/routes/productRoutes.js
src/components/TopBar/UserTopbar.css
src/pages/buyer/Dashboard.jsx

searching integrated with the backend now

searching integrated with the backend now

---

src/pages/buyer/UserDashboard.jsx

searching from the product implemented for user dashboard

searching from the product implemented for user dashboard

---

src/layouts/AdminLayout.jsx
src/layouts/SellerLayout.jsx

some change on the UI of seller layout

some change on the UI of seller layout

---

server/routes/productRoutes.js
src/pages/buyer/Dashboard.jsx

Searching errors fixed 

---

src/pages/buyer/Dashboard.jsx

conflicts resolved

---

src/pages/Login/LoginPage.jsx

seller error fixed

---

src/pages/buyer/UserDashboard.jsx

user dashboard error fixed

---

src/pages/buyer/Dashboard.jsx

Improve  the user experience  on the search box

Improve  the user experience  on the search box

---

src/pages/Login/LoginPage.jsx

password reset problem fixed

---

src/pages/buyer/UserDashboard.jsx

price sorting implemented for the user dashboard

price sorting implemented for the user dashboard

---

src/pages/buyer/UserDashboard.jsx

modification on user dashboard

modification on user dashboard

---

src/pages/buyer/UserDashboard.jsx

price sorting only  visible after the searching

price sorting only  visible after the searching 

---

src/pages/buyer/UserDashboard.jsx

the price sorting must be only visible when the search occurs

the price sorting must be only visible when the search occurs

---

src/components/TopBar/UserTopbar.jsx

the cart icon only shows 3 cart products when the page first loaded

the cart icon only shows 3 cart products when the page first loaded

---

server/controllers/requestController.js
server/index.js
server/migrations/20250203084500_requests table creation.js
server/routes/requestRoutes.js
src/App.jsx
src/pages/seller/Request.jsx

the seller cam make a request now

the seller cam make a request now

---

server/controllers/requestController.js
server/routes/requestRoutes.js
src/App.jsx
src/layouts/AdminLayout.jsx
src/pages/admin/requestedProducts.jsx
src/services/requestService.jsx

request the product to be inserted

request the product to be inserted

---

server/controllers/mailer.js
server/controllers/requestController.js
server/routes/requestRoutes.js
src/pages/admin/requestedProducts.jsx

request for the product approval and rejection implemented

request for the product approval and rejection implemented

---

server/migrations/20250205123240_update_catalog_brand_model_nullable.js
src/pages/admin/AddCatalog.jsx

the model and brand attributes changed  to support null values in the catalog listing

the model and brand attributes changed  to support null values in the catalog listing 

---

server/controllers/catalogController.js
server/migrations/20250205142005_add_dimension_to_catalogs.js
src/pages/admin/AddCatalog.jsx

adding unit for the catalog
